# Generated by Django 4.1.13 on 2024-08-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
