# Generated by Django 4.1.13 on 2024-08-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_appointment_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.appointmentslot'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='app.appointmentslot'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
