# Generated by Django 4.1.13 on 2024-08-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_appointmentslot_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
